[package]
name = "my-life-logger"
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true
authors.workspace = true
description.workspace = true

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "my_life_logger_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }
tauri-typegen = "0.4.0"

[dependencies]
domain.workspace = true
infrastructure.workspace = true
application.workspace = true

tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde_json = "1"
serde.workspace = true
anyhow = "1.0.101"
